
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (1, 'r4UwUyMzB3AB9MoY', 'A Figure among cyphers.', 'अंधों में काना राजा |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (2, 'TraHiVzyBy8YCgcL', 'All is well that ends well.', 'अंत भला सो भला |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (3, 'VZO8lnVQbGHJpm1S', 'He that is warm thinks all are so.', 'आप सुखी तो जग सुखी |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (4, 'jhD8c8WliDlEtFk0', 'Out of the frying pan into the fire.', 'आम से टपका बगल में अटका |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (5, 'uo9X79qTSqvGNiwI', 'Self praise is no recommendation.', 'अपने मुहं मियां मिट्ठू मत बनो |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (6, 'rGOwQrtGild2ehiy', 'Haste makes waste/Hurry spoils curry.', 'आगे दौड़ पीछे चौड |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (7, 'MRcrUBqs1TE5pa6b', 'Out of sight, out of mind.', 'आँख ओझल पहाड़ ओझल |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (8, 'S0aU7OEbZkZHPjoL', 'Necessity is the mother of invention.', 'आवश्यकता अविष्कार की जननी है |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (9, 'g5JJMrazcSEmRAcd', 'A blindman is no judge of colours.', 'अन्धा क्या जाने बसंत की बहार |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (10, 'D1G4KSY6trprmHZE', 'Blood is thicker than water.', 'अपना अपना');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (11, '2Aryl51MoD326032', 'Handsome is that handsome does.', 'अच्छा वही जो अच्छा कार्य करे |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (12, '3NMXxA9IGz7teDGu', 'Prevention is batter than cure.', 'इलाज से परहेज अच्छा |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (13, 'gamKR9hVTZlCl0Al', 'A drop of the ocean.', 'ऊंट के मुहं में जीरा |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (14, 'TB8VjJ57BuraNkrq', 'Example is better than precept.', 'उपदेश देने से स्वयं उपदेशों पर चलना बेहतर है |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (15, '8oyrwImHisntbuKL', 'It takes two make a row/quarrel.', 'एक हाथ से ताली नहीं बजती |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (16, 'R8EEgAoXxOKVhZWv', 'Two kill two birds with one stone.', 'एक पंथ दो काज |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (17, 'vJQOglApXXEwWjKf', 'Union is Strength.', 'एकता में बल |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (18, 'ckeU6AFinY9VxHfs', 'Silence is the best.', 'एक चुप सौ सुख |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (19, 'RWrR0zs7JkWKecsN', 'A single sheep infects the whole flock.', 'एक गंदी मछली सारे तालाब को गंदा कर देती है |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (20, 'mG2kMH9UkG4tN91K', 'Much cry, little wool.', 'ऊँची दुकान फीका पकवान |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (21, 'ZYz0Kd1IYwW1KfQh', 'Godness never goes unrewarded.', 'कर भला हो भला |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (22, 'py1NufuMhFCHR3zz', 'Uneasy lies the head that wears the crown.', 'कोठी वाला रोये');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (23, 'JZEe5uJe0IsMY4LI', 'Two of a trade seldom agree.', 'कुत्ते का कुत्ता बैरी |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (24, '7oIYhVF2crITesA6', 'Familiarity breeds contempt.', 'कद्र खोद देता है रोज का आना जाना |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (25, 'YdPhz2UKAmeribfG', 'practice makes a man perfect.', 'करत करत अभ्यास से जड्मुती होत सुजान |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (26, 'VVurwiOpvzadb4ku', 'An idle man’s brain is a devil’s workshop.', 'खाली बैठे सैतानी सूझे |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (27, 'kNDXisRnjKYyIUzM', 'Much ado about nothing.', 'खोदा पहाड़ निकली चुहिया |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (28, 'k8YurHv9HaoLzLUp', 'There is many a slip between the cup and the lip.', 'कानी के ब्याह में नौ सौ जोखिम |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (29, 'a4rnyqQos2zpPBcw', 'What cannot be cured.nust be endured.', 'गले पड़ा ढ़ोल बजाना ही पड़ता है |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (30, 'vUvNH6SnIVkxzOnq', 'To build castles in the air.', 'घर घोडा नकास मोल |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (31, 'DXg4B32QfFNIHgvV', 'When the cat is away, the mice will play.', 'घर वाला घर नहीं हमें किसी का दर नहीं |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (32, 'Wl0i7dHsPPHNHcMC', 'A nine day’s wonder.', 'चार दिन की चांदनी फिर अँधेरी रात |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (33, 'ByEZ6kahWwwTNTsu', 'Birds of a feather flock together.', 'चोर-चोर मौसेरे भाई |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (34, 'JKVGTMM7bFvu6HxG', 'Nothing succeeds like success.', 'चलती का नाम गाढ़ी |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (35, 'pRT2KapYj85e8mCT', 'Forbidden fruit is sweet.', 'चोरी का गुड मीठा होता है |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (36, 'WmfVni9svDIpH7wi', 'As you sow, so shall you reap.', 'जैसा करोगे वैसा भरोगे |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (37, 'nsbnA27ImvsLc96A', 'Barking dog seldom bite.', 'जो गरजते हैं वो बरसते नहीं |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (38, 'KFptPqAp2afaT3v4', 'Evil gotten, evil spent.', 'जैसा आया वैसा गया |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (39, '5DgOmsCUhUcIE2v0', 'Might is right.', 'जिसकी लाठी उसकी भैंस |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (40, 'Q8t2nFnqeYrens9C', 'No one knows the weight of another’s burben.', 'जाके पांव न फटी बुवाई सो क्या जाने पीर पराई |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (41, 'O3zFNObGaXXMpOz0', 'Tit for tat.', 'जैसे तो तैसा |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (42, 'G6fKpR3IDOjuaEcN', 'Hope sustains life.', 'जब तक सांस तब तक आस |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (43, 'RP12XWKiywjVu0YL', 'The deeper the well, the sweeter the water.', 'जितना गुड डालोगे उतना ही मीठा होगा |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (44, 'w9lajvafB9LkIoGE', 'Where there is a flower, there is a thorn.', 'जहाँ फूल वहां काँटा |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (45, 'EsBsrkoxEbvEZgcf', 'So many man, so many minds.', 'जितने मुहं उतनी ही बात |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (46, 'YkKgE0iZpYrQWbqL', 'A liar has no legs to stand upon.', 'झूठ के पांव नही होते |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (47, 'DMeBhNj9jxXWdERh', 'A drowning man catches at a straw.', 'डूबते को तिनके का सहारा |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (48, 'RE1JEhi5U37L42I2', 'Cowards die so many times before their death.', 'डरे सो मरे |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (49, 'oG8ZSrE91N6ghrej', 'Cut you coat according to your cloth.', 'तेते पावं पसारिये जेती लम्बी सौर |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (50, 'pmjB625aZj92hUvF', 'Your visits are few and far between.', 'तुम तो ईद के चाँद हो गये |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (51, 'CF2fSFLDdmIfK8zB', 'You are chips of the same block.', 'तुम एक ही थैली के चट्टे-बट्टे हो |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (52, 'XRYor0HUyjX6atym', 'Good health is above wealth.', 'तंदरुस्ती हजार नियामत|');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (53, 'UnDFcfxkfZFU7QWg', 'An empty vessel sounds high.', 'थोथा चना बाजे घना |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (54, 'dC6Fy5y8WkXVbcP7', 'A burnt child dreads the fire.', 'दूध का जला छाछ को भी फूंक कर पीता है |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (55, '0ds3MhOY4SVoi4V4', 'Poverty breeds stife.', 'दरिद्रता कहल की जड़ है |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (56, 'V0gfRHrGpMZsApot', 'Let us see which way the wind blows.', 'तेल देखो तेल की धार देखो |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (57, 'eAi5OyYIDB6KL9FY', 'Mone makes the mare go.', 'दाम बनाये काम |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (58, 'XIYP11HdTKWc7eaJ', 'Distance lands charm the viewer.', 'दूर के ढ़ोल सुहावने |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (59, 'H1pEEHGlzONrhc9V', 'There is something wrong at the bottom.', 'डाल में कुछ काला है |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (60, 'RhnrMhRUHNscCfQU', 'Money begets money.', 'धन से धन कमाया जाता है |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (61, 'mNON76feFBbvMasg', 'A rolling stone gathers no mass.', 'धोबी का कुत्ता घर का न घाट का |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (62, 'FSJI9gcRa538Y7qM', 'A bad workman quarrels with his tools.', 'नाच न जाने अगन टेढ़ा |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (63, '728PnIlUOe47YsBY', 'A bird in hand is batter than two in the bush.', 'नौ नकद न तेरह उधार |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (64, 'HalNEaKCWy8xehhb', 'A little knowledge is a dangerous thing.', 'नीम हकीम खतरे जान |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (65, 'eumjMfqlqz79stML', 'Do good and cast it into the river.', 'नेकी कर दलिया में डाल |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (66, 'X49UEMio6xnzitGQ', 'Adversity tries friends.', 'निर्धनता में मित्रों की पहचान होती है |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (67, '4sOf4DkoVINrPzav', 'It is hard to live in Rome and fight with the pope.', 'नदी में रहना और मगरमच्छ से बैर |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (68, 'ULQZHkraDLiMBLQr', 'A light purse is a heavy curse.', 'निर्धन की पत्नी सबकी भाबी |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (69, 'q727jGcXRNICluVC', 'Every dark clouds has a silver lining.', 'निराशा में भी आसा की झलक होती है |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (70, 'bvv53HFLi4iZ6Gsl', 'Ill got, ill spent.', 'पाप का धन प्रायश्चित में जाता है |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (71, 'i88ZjqW0ilNHIxC0', 'Think before you speak.', 'पहले तोलो फिर बोलो |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (72, 'cFo8I3AX9XZ80tSd', 'When God wills all winds bring rain.', 'परमात्मा देता है तो छप्पर फाड़ के देता है |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (73, 'riKGb4TO6TkO072I', 'Curst cows have short horns.', 'परमात्मा गंजे को नाख़ून न दे |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (74, '4mxHriE2rpNlTtJe', 'Charity begins at home.', 'पहले अपना फिर पराया |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (75, 'XVXvnoEMpgjiPzXD', 'A bas man is batter than a bad name.', 'बद अच्छा बदनाम बुरा |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (76, 'cncSaiMYE2FH8rF4', 'Let bygones by bygones.', 'बीती सो बीती |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (77, '3V19rLCgPuxsR3Q0', 'Make the best of every chance.', 'बहती गंगा में हाथ धोना |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (78, 'sYXyfd3LPcTtfhlq', 'Many a little makes a mickle.', 'बूंद-बूंद करके घड़ा भरता है |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (79, 'OFxESHNbhxSy084l', 'No pains, no gains.', 'बिना सेवा मेवा नहीं |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (80, '3p7WdlRAUb8Iwuvp', 'To cast pearls before swine.', 'बन्दर क्या जाने अदरक का स्वाद |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (81, 'xULr6Ov2nAEWKTAo', 'Too many cooks spoil the broth.', 'बहुत से जोगी मठ उजाड़ |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (82, 'Zzg2OihFxnME3gGw', 'Better alone than in a bad company.', 'बुरी संगत से अकेला भला |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (83, 'GKs5ppLzSSxXLIdo', 'It is batter to wear out than to rust out.', 'बेकार से बेगार भली |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (84, '5JFfMLpshOVENFwh', 'A nod to the wise and a rod to the foolish.', 'बुद्धिमान को संकेत और मुर्ख के लिए फटकार |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (85, 'NlorUEpXO1FUwIJB', 'When the purse is full friends are plenty.', 'बनी के सभी मित्र बिगड़ी का कोई नहीं |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (86, 'XNPETQ8OlE3qLBQa', 'Time once passed/gone can never be recalled.', 'बीता हुआ समय कभी हाथ नहीं आता |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (87, 'qgLxWI0JrJ8UsmIt', 'A ckosed mouth catches no fly.', 'बिना रोये माँ भी दूध नहीं देती |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (88, 'vbvQ6TSMV5EvSL37', 'Nip the evil in the bud.', 'बुराई को आरंभ में ही दबा दो |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (89, 't14dO6haBDtcrGeB', 'Crying in wilderness.', 'भैंस के आगे बीन बजाना |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (90, 'CGJDTeTXzqSeqjei', 'Something is better than nothing.', 'भागते चोर की लंगोटी ही सही |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (91, 'S6fj9AdD2qtiQk4g', 'Chance of fortune iss the lot of life.', 'भगवान की माया ');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (92, '0gNC4nlShm0TW2ak', 'A wolf in lamb’s clothing.', 'मुख में राम ');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (93, 'sD4nFmOsXSD3neKb', 'Man process, God disposes.', 'मेरे मन में कुछ और है ');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (94, 'p2f3Kn0YFaaVwsdg', 'Misfortunes never come alone/singly.', 'मुसीबत कभी अकेले नहीं आती |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (95, 'jJ29nvnqiMqcPHyA', 'Death keeps no calender.', 'म्रत्यु का कोई समय नहीं |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (96, 'Ylvr6UrZAQU0uvrq', 'A constant guest is never welcome.', 'मेहमान एक या दो दिन का होता है |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (97, 'bhXHiOGkOvtKbNK5', 'Man is known by the company he keeps.', 'मनुष्य अपनी संगति से पहचाना जाता है |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (98, 'NwpY2Vfio9rBPwzX', 'An open door tempts even a saint.', 'मुफ्त की शराब काजी को भी हलाल |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (99, 'eP6vnVaB7PVZIaHt', 'To err is human; to forgive divine.', 'मनुष्य गलती का पुतला है और भगवान का काम माफ़ करना है |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (100, '9J7hEZLPFb1Ijjsm', 'To make mountain of the mole hill.', 'राई का पर्वत बनाना |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (101, 'qByPeSZj5hfJqSwC', 'Wolves may lose their teeth but not their nature.', 'रस्सी जल गई पर बल न गया |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (102, 'I79Rc3n2vtn5Nv4V', 'Diamond cuts diamond.', 'लोहे को लोहा काटता है|');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (103, 'nXvV96tdkYNGfrUy', 'Riches have wings.', 'लक्ष्मी चंचला होती है |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (104, 'CiNrfHZvj3FaySZZ', 'Voice of the people is the voice of God.', 'लोगों की वाणी  इश्वर की वाणी |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (105, '6ZUH3fmt1DhhaJf9', 'Rod is the logic of fools.', 'लातों के भूत बातों से नहीं मानते |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (106, 'vpLGoxc5pfB9I3Qv', 'Truth is always bitter.', 'सच्ची बात चुभती है |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (107, '1844fynMexa6V0L9', 'It is very too late to mend.', 'सुबह का भुला यदि शाम को घर लोट आए तो उसे भूला नहीं कहते |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (108, 'jWe1fi49KEeKZNI7', 'Slow and steady wins the race.', 'सहज पके सो मीठा होए |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (109, 'nBorPKKuwgLha4ms', 'Beauty need no brnaments.', 'सुन्दरता को आभूषण की आवस्यकता नहीं |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (110, 'u12Iw99glHrbIFL2', 'Truth fears no test.', 'सांच को आंच नहीं |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (111, 'RUgzQWMhZm4Ojz7D', 'Everything looks pale to the jaundiced eye.', 'सावन के अंधे को हरा ही हरा दिखाई देता है |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (112, 'YVLfMCgkTtvOQf6f', 'Time is a great healer.', 'समय सब घावों का मरहम है |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (113, 'u0UpoK0amfx9odJc', 'Coming events cast their shadows before.', 'होनहार बिरवान के होत चिकने पात |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (114, 'Wmx41sZ19fdPDa1a', 'Measure for measure.', 'हत्या के बदले फासीं |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (115, 'vyfmikaGAi5qfzok', 'Rome was not built in a day.', 'हथेली पर दही नहीं जमती |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (116, 'NVOi7uwR5qiocer0', 'To build casties in the air.', 'हवाई किले बनाना |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (117, 'XXUtItmN1JYcoo9Q', 'All that glitters is not gold.', 'हाथी के दांत खाने के और दिखाने के और |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (118, 'BmI7SPsnO4SXv8mv', 'It’s no use to cry over spilt milk.', 'अब पछताए होत क्या जब चिडिया चुग गयी खेत |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (119, 'kV531hadfGkDLUrl', 'Every cock fights best on its own dunghill.', 'अपनी गली में कुत्ता भी शेर होता है |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (120, 'gU52h97C21XE3hgK', 'Death’s day is droom’s day.', 'आप मरे जग प्रलय |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (121, '9YY7MZsTh9A1ya2w', 'Out of sight, out of mind.', 'आँख ओझल पहाड़ ओझल |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (122, 'OOITuAbBctyJxih5', 'Do not put off till tomorrow.', 'आज का कार्य कल पर मत छोडो |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (123, 'iaEPcMu7RZqb5dQd', 'Better alone than in bad company.', 'कुसंगत से अकेला भला |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (124, '5H3yu7wNqPonH0BD', 'To carry coal to new castle.', 'उल्टे बांस बरेली को |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (125, 'iSTPn9xRTF0L7v6x', 'Sweep before your own door.', 'दुसरे के फटे में पांव नहीं देते |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (126, 'Ke2LNUG9q7ElHRto', 'Where there is well, there is a way.', 'जहाँ चाहा वहां राह |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (127, '0mIAoe9pv5HUeYr5', 'Nearver the church farther from God.', 'दिये तले अँधेरा |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (128, 'i6VtueciI1WLw3gU', 'A guilty conscience needs no accuser.', 'चोर की दाढ़ी में तिनका |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (129, 'PGM5unDSqVXIIVsS', 'Little drops make the ocean.', 'बूँद बूँद करके तालाब भरता है |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (130, 'QBAx5xcSHT0DKURv', 'God helps those who help themeselve.', 'ईस्वर उसकी सहायता करता है जो अपनी सहायता स्वेम करते हैं |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (131, '8xDfDNwigAvpPB52', 'Love begets love and hate begets hate.', 'घर्णा से घ्रणा पैदा होती है |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (132, 'kz3jQOBbxJj3HrEK', 'A friends in need is a friend indeed.', 'मित्र वही है जो मुसीबत मैं काम आता है |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (133, 'KuGobDXmnJ2P0RgP', 'Nothing venture, nothing have.', 'बिना खतरे लाभ नहीं |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (134, 'NKczyRFqTcqKhUFh', 'Honesty is the best policy.', 'इमानदारी अच्छी नीति है |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (135, 'KRWizVM536wVD809', 'Spend and God will send.', 'शक्कर खोर को परमात्मा शक्कर देता है |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (136, 'vPciSWhasaWPgcpe', 'A good name is batter than riches.', 'नाम बड़ा या दाम |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (137, 'VsnYF9YJ0g8BVNOC', 'If the sky falls, we shall catch larks.', 'न नौ मन तेल होगा न राधा नाचेगी |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (138, 'vMpOP3tTJzYhOHQI', 'Evil pursuits bring bad reputation.', 'कोयले की दलाली में मुहं काला |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (139, 'ONSoiUhqBYWn0S2j', 'Time blunts the edge of grief.', 'समय सब घावों का इलाज है |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (140, 'RAKEPIFX2RcKm81Y', 'Death with friends is a festival.', 'दोस्तों के साथ नरक भी स्वर्ग है |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (141, '25AXPJXcjd23v9vY', 'A prophet is seldom honoured in his own land.', 'घर को जोगी जोगडा बहार का जोगी सिद्ध |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (142, 'XFeRciAJrTEYR3C4', 'Evil can bot prosper for ever.', 'सौ दिन चोर के एक दिन साध का |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (143, 'AsFDD1VYiVuKJXpT', 'Pride goeth before a fall.', 'घमंडी का मुहं काला |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (144, 'EoxqM9pFNenzZE7l', 'east or west, home is the best.', 'अपने घर जैसा सुख कहीं भी नहीं |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (145, 'MNYsdxZ2moh298nI', 'He who hoards takes pains for others.', 'जोड़-जोड़ मर जाएँगे माल जमाई खायेगा |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (146, 'GM1uG7T0kXoNvcRr', 'Harping on the same string.', 'वही तुम वही तुम्हारा राग |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (147, '1zgZQ0g1tqNRhbCC', 'Virtue survives the grave.', 'नेकी करने के बाद याद आती है |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (148, 'aVxQulqdq2ZlpUpQ', 'Even walls have ears.', 'दीवार के भी कान होते हैं |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (149, 'KdDuauRIi0LiFKWV', 'It is a far cry.', 'अभी दिल्ली दूर है |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (150, 'LXrjhnKUzPs0uD7P', 'Grapes are sour.', 'हाथ न पहुंचे थूकौडी |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (151, 'vLWWkAMR0qheAW0Y', 'Do unto others as you wish to be done by them.', 'दुसरे के साथ वैसा ही व्यवहार करो जैसा तुम चाहते हो की वो तुमसे करें |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (152, 'avjMe5xwlSOnbcCC', 'Brain is better than brawn Wisdom is better than Strength.', 'अक्ल बड़ी के भैंस |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (153, 'GeHQfVQ88o5G84AT', 'Business is business.', 'व्यवसाय में लज्जा कैसी |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (154, 'fmABhuP2qWVHX3fg', 'Every tide has its ebb, he who rises, must fall.', 'हर उन्नति के उपरांत अवनति |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (155, 'RCVPBZB38zXFTAGQ', 'A traitor is the worest enemy.', 'घर का भेदी लंका ढाए |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (156, 'SzGx87EBa0X8WlrH', 'When the two bulls fight, it is the grass that suffers.', 'गेहूं के साथ घुन भी पिस जाता है |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (157, '5XGleZ9q6efisARj', 'Let the sleeping dogs lie.', 'भिडों के छते को मत छेड़ो |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (158, 'akdfl77yrtzFjXrf', 'Greed is a curse.', 'लालच बुरी बात है |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (159, 'y0ELwrI4EvJiPScg', 'Pen is mightier than the sword.', 'तलवार से कलम बड़ी है |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (160, 'YjvwJwHsBDGfpspX', 'Money saved, is money earned.', 'जो बचाया सो कमाया |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (161, 'tw3KDMgh62ZIZPGV', 'Knowledge is power.', 'विद्या सबसे बड़ा धन है |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (162, 'TmExhHucgswbq6yx', 'An upstart always grows haughty.', 'कुत्ते को घी हजम नहीं होता |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (163, 'xwKbvD1ls9Szds4X', 'A talk of chalk and you talk of cheese.', 'सवाल गंदम जबाब चना |');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (164, 'bTLcaXup96aIipBp', 'A leopard can not change it’s spots.', 'लकीर का फकीर');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (165, 'y5S0SGRhuEvAugKC', 'Herd Race, Mob Mentality.', 'भेड़ चाल');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (166, '2ZNmKWWdoU8MCay9', 'While In Rome Do As Romads Do.', 'जहाँ का पीवे पानी');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (167, 'EjOy6QwrY3V9aaYz', 'As You Sow, So Shall You Reap.', 'जैसी करनी');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (168, 'Vvyh4AZxoixEa1Om', 'A thing is valued where it belongs.', 'जंगल में मोती की कदर नहीं होती');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (169, 'p3g19EPls0vZQ1LZ', 'To The Good The World Appears Good.', 'आप भला तो जग भला');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (170, 'lsrXHDunGBmk3awU', 'An Empty Vessel Makes Much Noise.', 'थोथा चना बाजे घना');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (171, 'upreIgqwXQVkrg3L', 'Helath Is Wealth.', 'तंदरुस्ती हजार नियामत है');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (172, 'yKSfwkwKRHsPLynv', 'No Pain, No Gain.', 'काया को दुःख दिए बिना कोई काम नहीं सुधरता');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (173, 'RVQLHotQhoRqTUIF', 'Time Once Lost Cannot Be Regained.', 'गया वक्त फिर हाथ नहीं आता');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (174, '0DQnbZKpYDz5UCMM', 'Society Moulds Man.', 'खरबूजे को देखकर खरबूजा रंग नही बदलता है');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (175, 'lsVOORmnl8dzOITD', 'Union Is Strength.', 'एक और एक ग्यारह होते हैं');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (176, '668xTB7eAYWpHbbb', 'Fools Praise Fools.', 'गधे को गधा खुजलाता है');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (177, 'eGzWT07JVuFlc7iV', 'Many Heads Many Minds.', 'अपनी अपनी डफली');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (178, 'otFqai5oWP2FlHS6', 'Barking Dogs Seldom Bite.', 'जो गरजते हैं सो बरसते नहीं');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (179, 'JiO7zpfJhK3xjstS', 'It Is No Use Building Castles In The Air.', 'मन के लड्डुओं से भूक नहीं मिटती');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (180, '0fl0aXXJHTgMtvUt', 'Penny Wise Pound Foolish.', 'गवांर गत्रा न दे');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (181, 'TVR9xOqQpN8im3wn', 'Give Loan, Enemy Own.', 'उधार दीजे');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (182, '3uQjnXNbzzqIgSyo', 'Birds Of a Feather Flock Together.', 'एक थैली के चट्टे बट्टे');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (183, 'sGIblm6r4iGMVC2L', 'Where There is a Will, There Is a Way.', 'जहाँ चाह-वहां राह');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (184, 'p5gZeLTZM58AOYcG', 'A Bad Carpenter Quarrels With Hi tool.', 'नाच न जाने आँगन टेढा');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (185, 'ccggJYMMjTi4QCem', 'Silence Is Half Consent.', 'चुप माने');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (186, '9nJW7QeRCo22UrkP', 'An Empty Vessel Makes Much Noise.', 'अधजल गगरी छलकत जाए');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (187, 'bSQLsViuu6A9d7wi', 'A Man Is a Slave to His Stomach.', 'आदमी पेट का दास23');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (188, 'ueMbG9N19GnS62wM', 'A Brunt Child Dreads The Fire./Once Bitten Twice Shy.', 'दूध का जला छाछ फूंक-फूंक कर पीता है');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (189, 'lGTssiAFaVhAOVF4', 'A Honey tongue.', ' a Heart Of Gall ');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (190, 'fQBXOd0RfhLAf2hh', 'A Little Knowledge Is a Dangerous thing .', 'नीम हकीम खतरा-ए-जान');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (191, 'XbIOmjXNa5I2Bg5X', 'All’s Well That Ends Well', 'अंत भला तो सब भला');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (192, 'bfvxsMrZJJ02DHL6', 'Style Makes The Man .', 'कपडे देखर इज्जत मिलती है');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (193, '5b1wbH7JKmKN2Tg8', 'One Nail Drivers Another .', 'कांटे से कांटा निकलता है');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (194, 'nEPW54vaj99D6Hd3', 'Truth Lies At The Bootom of a Well .', 'मोती गहरे पानी मैं होता है');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (195, '5Y71tBq0PqIZGprm', 'There Is a Time For Everything .', 'हर चीज का वक्त होता है');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (196, 'Dd8Ash6Xxwe9ShCA', 'One Lie leads to Another .', 'झूठ का अंत नहीं');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (197, 'I3hfjg0jgvK2Cmww', 'It Takes All Sorts To Make The World .', 'इ संसार में हर तरह के लोग होते हैं');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (198, 'cgJTmJxp8V29bDIK', 'It Takes To Make A Quarrel .', 'ताली दोनों हाथों से बजती है');
INSERT INTO public.idioms_tbl (_id, id, idiom_eng, idiom_hin) VALUES (199, 'SvEZQUbZjULcernJ', 'A Friend In Need Is a Friend Indeed .', 'मित्र वही जी मुसीबत में काम आये');


